apiVersion: v1
kind: Secret
metadata:
  name: demo-htpasswd-secret
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    demo-clusteradmin:$2y$05$GENERATE_WITH_HTPASSWD
    demo-clusterreader:$2y$05$GENERATE_WITH_HTPASSWD
    demo-admin:$2y$05$GENERATE_WITH_HTPASSWD
    demo-editor:$2y$05$GENERATE_WITH_HTPASSWD
    demo-viewer:$2y$05$GENERATE_WITH_HTPASSWD
