apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-debug-namespace-rbac
  namespace: acm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: debug-namespace-rbac
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - "openshift-debug-*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: debug-team-edit
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: edit
                subjects:
                  - apiGroup: rbac.authorization.k8s.io
                    kind: Group
                    name: debug-team
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-debug-namespace-rbac
  namespace: acm-policies
placementRef:
  name: all-managed-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-debug-namespace-rbac
    kind: Policy
    apiGroup: policy.open-cluster-management.io
