apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      externalLabels:
        cluster_name: production-east
      remoteWrite:
      - url: "https://noc-prometheus.example.com:9090/api/v1/write"
        tlsConfig:
          insecureSkipVerify: false
          ca:
            name: noc-prometheus-ca
            key: ca.crt
