apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-catalog-pull-secret
  namespace: acm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: catalog-pull-secret
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: curated-catalog-pull
                  namespace: openshift-marketplace
                type: kubernetes.io/dockerconfigjson
                data:
                  .dockerconfigjson: '{{hub fromSecret "acm-policies" "quay-robot-creds" ".dockerconfigjson" hub}}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-catalog-pull-secret
  namespace: acm-policies
placementRef:
  name: all-managed-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-catalog-pull-secret
    kind: Policy
    apiGroup: policy.open-cluster-management.io
