apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-restrict-catalog-types
  namespace: acm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: restrict-catalog-types
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: Console
                metadata:
                  name: cluster
                spec:
                  customization:
                    developerCatalog:
                      types:
                        state: Disabled
                        disabled:
                          - HelmChart
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-restrict-catalog-types
  namespace: acm-policies
placementRef:
  name: all-managed-clusters
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-restrict-catalog-types
    kind: Policy
    apiGroup: policy.open-cluster-management.io
