apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: webapp-team-amq-streams
  namespace: webapp-team
spec:
  channel: stable
  installPlanApproval: Manual
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
