apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-admin
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  - operatorgroups
  - installplans
  - clusterserviceversions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - packages.operators.coreos.com
  resources:
  - packagemanifests
  verbs:
  - get
  - list
  - watch
