apiVersion: v1
kind: Namespace
metadata:
  name: simulated-bmh
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: simulated-bmh
  namespace: simulated-bmh
spec:
  runStrategy: Halted
  template:
    metadata:
      labels:
        app: simulated-bmh
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              macAddress: "02:00:00:00:00:01"
              bridge: {}
      networks:
        - name: default
          multus:
            networkName: default/lab-vlan6-vm
      volumes:
        - name: rootdisk
          dataVolume:
            name: simulated-bmh-rootdisk
  dataVolumeTemplates:
    - metadata:
        name: simulated-bmh-rootdisk
      spec:
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
        source:
          blank: {}
