apiVersion: v1
kind: Secret
metadata:
  name: simulated-bmh-userdata
  namespace: openshift-machine-api
type: Opaque
stringData:
  userData: |
    #cloud-config
    user: fedora
    password: changeme
    chpasswd:
      expire: false
    ssh_pwauth: true
    packages:
      - qemu-guest-agent
    runcmd:
      - systemctl enable --now qemu-guest-agent
